### ISSUE TITLE
error during setup 

### ISSUE THREAD

**Issue by PabloGamerYTB** [nlscc/unpyarmor#2]
Hey I have this error during the setup (I already installed Visual Studio Build Tools with link)

error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

**Comment by crinny** [comment]
You need to install pycryptodome instead of pycrypto as the latter one won't work on Windows

**Comment by nlscc** [comment]
This seems to be a quite common issue with pip on Windows. I updated the code to use pycryptodome (fed3a81) instead, maybe that will help, but I don't use Windows so I can't test anything.
However in my experience Python on Windows is not the best, so you could try using it through WSL.

**Comment by PabloGamerYTB** [comment]
The setup work perfect now!
