### ISSUE TITLE
ModuleNotFoundError: No module named 'unpyarmor'

### ISSUE THREAD

**Issue by PabloGamerYTB** [nlscc/unpyarmor#3]
The setup works well, but now I have this error....

![image](https://user-images.githubusercontent.com/40907380/87941000-74033c00-ca68-11ea-9406-badc10b38b4c.png)

**Comment by Thonleb** [comment]
![image](https://user-images.githubusercontent.com/66848687/88076895-a2f0df00-cb48-11ea-8f8d-a3d232655493.png)
Same here
